import closeT from './assets/images/closeT.svg'
import icDashboard from './assets/images/ic-dashboard.svg'
import icDocuments from './assets/images/ic-documents.svg'
import icFacility from './assets/images/ic-facility.svg'
import icMachines from './assets/images/ic-machines.svg'
import mineT from './assets/images/mineT.svg'
import openT from './assets/images/openT.svg'
import machineImg from './assets/images/Machine-Image.png'
// import Frame from './assets/images/Frame'

export const menuItems = [
  { id: 1, title: 'Open Tickets', img: openT },
  { id: 2, title: 'My Tickets', img: mineT },
  { id: 3, title: 'Closed Tickets', img: closeT },
  { id: 4, title: 'Machines', img: icMachines },
  { id: 5, title: 'Facilities', img: icFacility },
  { id: 6, title: 'Documents', img: icDocuments },
  { id: 7, title: 'Analytics', img: icDashboard },
]
export const singleTabs = [
  { id: 1, title: 'Machine Details' },
  { id: 2, title: 'Documentation' },
  { id: 3, title: 'History' },
  { id: 4, title: 'Preventive Maintenance' },
]

export const machineTabItems = [
  {
    id: '1',
    title: 'Super packer 1800',
    serial: '112450 3331',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line B',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '47',
  },
  {
    id: '2',
    title: 'Super packer 1800',
    serial: '112450 3332',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line C',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '58',
  },
  {
    id: '3',
    title: 'Super packer 1800',
    serial: '112450 3333',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line B',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '70',
  },
  {
    id: '4',
    title: 'Super packer 1800',
    serial: '112450 3334',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line A',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '56',
  },
  {
    id: '5',
    title: 'Super packer 1800',
    serial: '112450 3335',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line C',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '7',
  },
  {
    id: '6',
    title: 'Super packer 1800',
    serial: '112450 3336',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line B',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
    createdM: '2',
  },
  {
    id: '7',
    title: 'Super packer 1800',
    serial: '112450 3337',
    company: 'Apple juce factory Rothenburg',
    category: 'Production Line A',
    img: machineImg,
    createdM: '3',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '8',
    title: 'Super packer 1800',
    serial: '112450 3337',
    company: 'Apple juce factory Rothenburg',
    createdM: '1',
    category: 'Line Template',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '9',
    title: 'Super packer 1800',
    createdM: '42',
    serial: '112450 3337',
    company: 'Apple juce factory Rothenburg',
    category: 'Machine Template',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '10',
    title: 'Super packer 180',
    createdM: '4',
    serial: '112450 3337',
    category: 'Machine Template',
    company: 'Apple juce factory Rothenburg',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '11',
    title: 'Super packer 1800',
    createdM: '8',
    serial: '112450 3337',
    category: 'Machine Template',
    company: 'Apple juce factory Rothenburg',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '12',
    title: 'Super packer 1800',
    createdM: '6',
    serial: '112450 3337',
    category: 'Machine Template',
    company: 'Apple juce factory Rothenburg',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '13',
    title: 'Super packer 1800',
    createdM: '43',
    serial: '112450 3337',
    category: 'Line Template',
    company: 'Apple juce factory Rothenburg',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
  {
    id: '14',
    title: 'Super packer 1800',
    createdM: '23',
    serial: '112450 3337',
    company: 'Apple juce factory Rothenburg',
    category: 'Line Template',
    img: machineImg,
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium sapiente illo blanditiis expedita vel beatae qui maxime! Nisi, consectetur nostrum?',
  },
]
